### ISSUE TITLE
Question about Training Observation Encoder. 

### ISSUE THREAD

**Issue by Precola** [UnrealTracking/ToM2C#1]
In the process of network training, does the encoder network train together through ToM network? Or does the encoder net have its own loss?

**Comment by yuanfei-Wang** [comment]
Sorry for the late response. I didn't notice the issue.
As mentioned in the paper, the ToM net and the other networks(including encoder, message sender and decision-maker) are trained separately. The ToM net is supervised by the ToM loss, while the other parts are trained through RL loss. So for your question, the encoder network is **frozen** when we train the ToM net. The encoder net is trained end-to-end under the RL loss, so it does not have its own loss.
